CodingByJerez\MondialRelayBundle\Model\RecherchePointRelaisModel:
    properties:
        paysCode:
            - NotBlank:
                message: validation.recherche_point_relais.pays_code.blank
            - Country:
                message: validation.recherche_point_relais.pays_code.country
        numPointRelais:
            - Type:
                type: integer
                message: validation.recherche_point_relais.num_point_relais.type
            - Length:
                max: 6
                maxMessage: validation.recherche_point_relais.num_point_relais.length_max
        ville:
            - Type:
                type: string
            - Length:
                min: 2
                max: 25
                minMessage: validation.recherche_point_relais.ville.length_min
                maxMessage: validation.recherche_point_relais.ville.length_max
        codePostal:
            - Type:
                type: string
        latitude:
            - Type:
                type: float
            - Expression:
                expression: "value and this.getLongitude()"
                message: validation.recherche_point_relais.latitude.expression
        longitude:
            - Type:
                type: float
            - Expression:
                expression: "value and this.getLatitude()"
                message: validation.recherche_point_relais.longitude.expression
        taille:
            - Choice:
                choices: [XS, S, M, L, XL, XXL, 3XL]
                message: validation.recherche_point_relais.taille.choises
        poids:
            - Type:
                type: integer
                message: validation.recherche_point_relais.poids.type
            - Length:
                max: 6
                maxMessage: validation.recherche_point_relais.poids.length_max
        action:
           - Choice:
                choices: [REL, 24R, 24L, 24X, DRI]
                message: validation.recherche_point_relais.action.choises
        delaiEnvoi:
            - Type:
                type: integer
                message: validation.recherche_point_relais.delai_envoi.type
            - Length:
                max: 2
                maxMessage: validation.recherche_point_relais.delai_envoi.length_max
        rayonRecherche:
            - Type:
                type: integer
                message: validation.recherche_point_relais.rayon_recherche.type
            - Length:
                max: 4
                maxMessage: validation.recherche_point_relais.rayon_recherche.length_max
        typeActivite:
            - Regex:
                pattern: '/^(\d{3},|\d{3})*$/'
                match:   false
                message: validation.recherche_point_relais.type_activite.regex


CodingByJerez\MondialRelayBundle\Model\AdressetModel:
    properties:
        langage:
            - NotBlank:
                message: validation.adresse.langage.blank
            - Language:
                message: validation.adresse.langage.language
        identite:
            - NotBlank:
                message: validation.adresse.adresse_ligne_1.blank
            - Type:
                type: string
            - Length:
                min: 2
                max: 32
                minMessage: validation.adresse.adresse_ligne_1.length_min
                maxMessage: validation.adresse.adresse_ligne_1.length_max
        identiteComplement:
            - Type:
                type: string
            - Length:
                min: 2
                max: 32
                minMessage: validation.adresse.adresse_ligne_2.length_min
                maxMessage: validation.adresse.adresse_ligne_2.length_max
        adresse:
            - NotBlank:
                message: validation.adresse.adresse_ligne_3.blank
            - Type:
                type: string
            - Length:
                min: 2
                max: 32
                minMessage: validation.adresse.adresse_ligne_3.length_min
                maxMessage: validation.adresse.adresse_ligne_3.length_max
        adresseComplement:
            - Type:
                type: string
            - Length:
                min: 2
                max: 32
                minMessage: validation.adresse.adresse_ligne_4.length_min
                maxMessage: validation.adresse.adresse_ligne_4.length_max
        ville:
            - NotBlank:
                message: validation.adresse.ville.blank
            - Type:
                type: string
            - Length:
                min: 2
                max: 26
                minMessage: validation.adresse.ville.length_min
                maxMessage: validation.adresse.ville.length_max
        codePostal:
            - NotBlank:
                message: validation.adresse.cp.blank
            - Type:
                type: string
        paysCode:
            - NotBlank:
                message: validation.adresse.pays.blank
            - Country:
                message: validation.adresse.pays.country
        tel:
            - NotBlank:
                message: validation.adresse.tel_1.blank
            - Type:
                type: string
        tel2:
            - Type:
                type: string
        courriel:
            - Email:
                message: validation.adresse.courriel.email



CodingByJerez\MondialRelayBundle\Model\Creation\ExpeditionModel:
    properties:
        modeCollecte:
            - NotBlank:
                message: validation.expedition.mode_collecte.blank
            - Choice:
                choices: [CCC, CDR, CDS, REL]
                message: validation.expedition.mode_collecte.choises
        modeLivraison:
            - NotBlank:
                message: validation.expedition.mode_livraison.blank
            - Choice:
                choices: [LCC, LD1, LDS, 24R, 24L, 24X, ESP, DRI]
                message: validation.expedition.mode_livraison.choises
        numeroDossier:
            - Regex:
                pattern: '/^[0-9a-zA-Z_ -]+$/'
                match:   false
                message: validation.expedition.numero_dossier.regex
            - Length:
                max: 15
                maxMessage: validation.expedition.numero_dossier.lengthMax
        numeroClient:
            - Regex:
                pattern: '/^[0-9a-zA-Z_ -]+$/'
                match:   false
                message: validation.expedition.numero_client.regex
            - Length:
                max: 9
                maxMessage: validation.expedition.numero_client.lengthMax
        poids:
            - NotBlank:
                message: validation.expedition.poids.blank
            - Type:
                type: integer
                message: validation.expedition.poids.type
            - Length:
                min: 3
                max: 7
                minMessage: validation.expedition.poids.length_min
                maxMessage: validation.expedition.poids.length_max
        longueur:
            - Type:
                type: integer
                message: validation.expedition.longueur.type
            - Length:
                max: 3
                maxMessage: validation.expedition.longueur.length_max
        taille:
            - Choice:
                choices: [XS, S, M, L, XL, XXL, 3XL]
                message: validation.expedition.taille.choice
        nombreColis:
            - NotBlank:
                message: validation.expedition.nombre_colis.blank
            - Type:
                type: integer
                message: validation.expedition.nombre_colis.type
            - Length:
                max: 2
                maxMessage: validation.expedition.nombre_colis.length_max
        contreRemboursementMontant:
            - NotBlank:
                message: validation.expedition.contre_remboursement_montant.blank
            - Type:
                type: integer
                message: validation.expedition.contre_remboursement_montant.type
            - Length:
                max: 7
                maxMessage: validation.expedition.contre_remboursement_montant.length_max
        contreRemboursementDevise:
            - Choice:
                choices: [EUR]
                message: validation.expedition.contre_remboursement_devise.choice
        expeditionValeur:
            - Type:
                type: integer
                message: validation.expedition.expedition_valeur.type
            - Length:
                max: 7
                maxMessage: validation.expedition.expedition_valeur.length_max
        expeditionDevise:
            - Choice:
                choices: [EUR]
                message: validation.expedition.expedition_devise.choice

        collectePointRelaisPays:
            - Expression:
                expression: "!(this.getModeCollecte() in ['REL'] and !value)"
                message: validation.expedition.collecte_point_relais_pays.expression
            - Country:
                message: validation.expedition.collecte_point_relais_pays.country
        collectePointRelaisID:
            - Expression:
                expression: "!(this.getModeCollecte() in ['REL'] and !value)"
                message: validation.expedition.collecte_point_relais_id.expression
            - Type:
                type: integer
                message: validation.expedition.collecte_point_relais_id.type
            - Length:
             #   min: 6
                max: 6
             #   minMessage: validation.collecte_point_relais_id.length_min
                maxMessage: validation.expedition.collecte_point_relais_id.length_max
        livraisonPointRelaisPays:
            - Expression:
                expression: "!(this.getModeLivraison() in ['24R', '24L', 'DRI'] and !value)"
                message: validation.expedition.livraison_point_relais_pays.expression
            - Country:
                message: validation.expedition.livraison_point_relais_pays.country
        livraisonPointRelaisID:
            - Expression:
                expression: "!(this.getModeLivraison() in ['24R', '24L', 'DRI'] and !value)"
                message: validation.expedition.livraison_point_relais_id.expression
            - Type:
                type: integer
                message: validation.expedition.livraison_point_relais_id.type
            - Length:
                #min: 6
                max: 6
               # minMessage: validation.livraison_point_relais_id.length_min
                maxMessage: validation.expedition.livraison_point_relais_id.length_max
        demandeAvisage:
            - Choice:
                choices: [O, N]
                message: validation.expedition.demande_avisage.choice
        demandeReprise:
            - Choice:
                choices: [O, N]
                message: validation.expedition.demande_reprise.choice
        tempsMontage:
            - Type:
                type: integer
                message: validation.expedition.temps_montage.type
            - Length:
                max: 3
                maxMessage: validation.expedition.temps_montage.length_max
        demandeRendezVous:
            - Choice:
                choices: [O, N]
                message: validation.expedition.demande_rendez_vous.choice
        assurance:
            - Length:
                max: 1
                maxMessage: validation.expedition.assurance.length_max
        instructions:
            - Type:
                type: String
            - Length:
                max: 31
                maxMessage: validation.expedition.instructions.length_max


CodingByJerez\MondialRelayBundle\Model\Creation\EtiquetteModel:
        texte:
           - Regex:
                pattern: '/^([^<>&]{3,30})(\(cr\)[^<>&]{0,30}){0,9}$/'
                match:   false
                message: etiquette.text.regex
